### ISSUE TITLE
Docs in english

### ISSUE THREAD

**Issue by Halfeld** [warpcgd/vue-slider#3]
Hello,

I found this project on Github trending and I wanted to use :D, but exists or will be exists some documentation in english?

Igor

**Comment by warpcgd** [comment]
@Halfeld  Hello , I will translate it into English later , thanks for your advice :D

**Comment by Halfeld** [comment]
Fantastic!

**Comment by warpcgd** [comment]
@Halfeld,Here you are, I have translated it

**Comment by Halfeld** [comment]
@warpcgd Pretty cool! Thanks :D
