### ISSUE TITLE
有vue2.0的版本吗

### ISSUE THREAD

**Issue by fangdown** [warpcgd/vue-slider#4]
里面的dispatch  失效了，什么时候升级一下到2.0

**Comment by mengchen129** [comment]
同问

**Comment by warpcgd** [comment]
@fangdown @mengchen129  会尽快推出2.0版本

**Comment by mengchen129** [comment]
楼主的slider组件功能确实很强大，不过鉴于常用的就是横向滑动，因此自己写了一个slider的简单实现，目前只支持移动端，只支持展示图片。 [vue-image-slider](https://github.com/mengchen129/vue-image-slider)

**Comment by warpcgd** [comment]
@mengchen129 写的挺好的,加上循环滚动就可以通用了
